{
  lib,
  buildGoModule,
}:
let
  distName = "nrdot-collector";
  version = "2.0.0";
in
buildGoModule rec {
  pname = distName;
  inherit version;

  # The distribution sources are generated by `ocb` (the OpenTelemetry
  # Collector Builder) from the `nrdot-collector-releases` repo. ocb shells out
  # to `go mod tidy`, which requires network access to proxy.golang.org, so the
  # generation cannot run in Nix's sandbox on Linux builders. The generated,
  # self-contained Go module is therefore committed under ./generated and
  # regenerated with:
  #
  #   ocb --skip-compilation=true --config manifest.yaml
  #
  # inside `distributions/nrdot-collector/` of a checkout of
  # newrelic/nrdot-collector-releases at tag ${version}.
  src = ./nrdot-collector/generated;

  # The generated module lives at the root of this source directory.
  modRoot = ".";

  vendorHash = "sha256-WxbDR0OumDVpKw2XtZ3bTxc8hPT2ChCs22MFlhP3nlg=";

  ldflags = [
    "-s"
    "-w"
  ];

  # The TestValidateConfigs tests download new dependencies for a modified go.mod. Nix doesn't allow network access so skipping.
  checkFlags = [ "-skip TestValidateConfigs" ];

  env.CGO_ENABLED = "0";

  meta = with lib; {
    description = "The New Relic distribution of the OpenTelemetry Collector";
    homepage = "https://github.com/newrelic/nrdot-collector-releases.git";
    changelog = "https://github.com/newrelic/nrdot-collector-releases/blob/${version}/CHANGELOG.md";
    license = licenses.asl20;
    maintainers = with maintainers; [ DavSanchez ];
    mainProgram = "nrdot-collector";
    platforms = platforms.all;
  };
}
